server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://mainproject27team.c16y5acx5nnq.ap-northeast-2.rds.amazonaws.com:3306/mainproject?serverTimezone=Asia/Seoul
    username: admin
    password: TZJrQnSUmZGHc2Fm0Vjw
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    baseline-on-migrate: true
    enabled: false
  # 임시비밀번호발급 >> 보내는 이메일주소 변경. 이름으로 표시할수 있는지 알아볼 것.
  mail:
    host: smtp.naver.com
    port: 465
    username: likedubu@naver.com
    password: peanut610!
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 557076266512-26m0oio1d43tguk02g1fur7umuarvse2.apps.googleusercontent.com
            client-secret: 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
            scope:
              -profile
              -email #openId 가 있으면 OpenId provider로 인식하기 때문에 이렇게되면 openIdprovider가 아닌 카카오,네이버와 나누어서 service를 만들어야 한다.




mail:
  address:
    admin: likedubu@naver.com

jwt:
  #  key: ${JWT_SECRET_KEY}   # 민감한 정보는 시스템 환경 변수에서 로드한다.
  key: davin1234123412341234123412341234
  access-token-expiration-minutes: 420
  refresh-token-expiration-minutes: 420
