server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/main027?serverTimezone=Asia/Seoul
    username: root
    password: 12345678
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
