server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/main027?serverTimezone=Asia/Seoul
    username: root
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
  flyway:
    baseline-on-migrate: true
    enabled: false

mail:
  address:
    admin: likedubu@naver.com

jwt:
#  key: ${JWT_SECRET_KEY}   # 민감한 정보는 시스템 환경 변수에서 로드한다.
  key: davin1234123412341234123412341234
  access-token-expiration-minutes: 420
  refresh-token-expiration-minutes: 420


cloud: # AWS 계정 설정
  aws:
    region:
      static: ap-northeast-2
    s3:
      credentials:
        access-key: AKIAXPWH6LGUCFTOATC2
        secret-key: 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
    stack:
      auto: false