server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://mainproject27team.c16y5acx5nnq.ap-northeast-2.rds.amazonaws.com:3306/mainproject?serverTimezone=Asia/Seoul
    username: admin
    password: ENC(D4/hy+/wLxdwV/oo+B5uY6fhvuEej6NgFVEPd+j/tRA=)
  jpa:
#    hibernate:
#      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
  flyway:
    baseline-on-migrate: true
    enabled: true

mail:
  address:
    admin: likedubu@naver.com

jwt:
  #  key: ${JWT_SECRET_KEY}   # 민감한 정보는 시스템 환경 변수에서 로드한다.
  key: ENC(LjuWVsYfzpKEDBb7y1w6/Q6352rGfYBVIT0qJfktJwael4SdhN5XG86bhnIkVa0c)
  access-token-expiration-minutes: 420
  refresh-token-expiration-minutes: 420

cloud: # AWS 계정 설정
  aws:
    region:
      static: ap-northeast-2
    s3:
      credentials:
        access-key: ENC(O/SV8aFGe4ASaXjpRb+j2yNBoDuQNcMHpmkq4hQC/sk=)
        secret-key: ENC(lbA3Dm/e0/xvi0/M5/WkO1VKrzpKPYRf1+zdc5ocaJNF6icBJdlD2GJwXC7lZDYldorBzT2Z7qU=)
    stack:
      auto: false

jasypt: #패스워드 암호화/복호화 키
  encryptor:
    password: ${jasypt_password}