server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/main027?serverTimezone=Asia/Seoul
    username: root
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
mail:
  address:
    admin: likedubu@naver.com

jwt:
#  key: ${JWT_SECRET_KEY}   # 민감한 정보는 시스템 환경 변수에서 로드한다.
  key: davin1234123412341234123412341234
  access-token-expiration-minutes: 30
  refresh-token-expiration-minutes: 420
